### ISSUE TITLE
[xdmod 6.6.0 Centos 7.3] Failed to create admin user:

### ISSUE THREAD

**Issue by dspatil7768** [ubccr/xdmod#162]
I'm facing issue while creating admin user in XDMoD 6.6.0.

```
========================================================================
Create Admin User
========================================================================

Username: admin
Password:
(confirm) Password:
First name: admin
Last name: admin
Email address: xyz@gmail.com

Failed to create admin user:

The public role user cannot be saved.

#0 /usr/share/xdmod/classes/OpenXdmod/Setup/AdminUserSetup.php(48): XDUser->saveUser()
#1 /usr/share/xdmod/classes/OpenXdmod/Setup/Menu.php(69): OpenXdmod\Setup\AdminUserSetup->handle()
#2 /usr/bin/xdmod-setup(38): OpenXdmod\Setup\Menu->display()
#3 /usr/bin/xdmod-setup(23): main()
#4 {main}
```
Suggest me if I'm going wrong ? 
Thank you

**Comment by jtpalmer** [comment]
Did you initialize your database?  Try running this query in MySQL:

```sql
SELECT * FROM moddb.Roles;
```

**Comment by dspatil7768** [comment]
Yes, I initialized it earlier using `xdmod-setup`

```
MariaDB [moddb]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mod_hpcdb          |
| mod_logger         |
| mod_shredder       |
| moddb              |
| modw               |
| modw_aggregates    |
| modw_filters       |
| mysql              |
| performance_schema |
| test               |
| warewulf           |
+--------------------+
12 rows in set (0.01 sec)

MariaDB [moddb]> SELECT * FROM moddb.Roles;
Empty set (0.00 sec)

```

**Comment by dspatil7768** [comment]
Got it. During `xdmod-setup` while creating and initializing databases I forgot to enter yes among one of the databases.
