### ISSUE TITLE
ressources.json syntax error

### ISSUE THREAD

**Issue by sazearte** [ubccr/xdmod#30]
Hello, i try Open XDMoD in centos 7 with php5.

When i configure ressources.json i have this error:
```
[root@localhost slurm]# xdmod-shredder -r mycluster -f slurm -i /tmp/slurm.log
2017-01-20 09:52:51 [notice] xdmod-shredder start (process_start_time: 2017-01-20 09:52:51)
2017-01-20 09:52:51 [critical] Failed to create shredder: Failed to decode file '/etc/xdmod/resources.json': Syntax error
Contents = [
    {
        "resource": "mycluster",
        "name": "My Cluster"
        "description": "Our first HPC resource",
        "resource_type_id": 1
    },
    {
        "resource": "resource2",
        "name": "Resource 2",
        "resource_type_id": 2,
        "pi_column": "account_name"
    },
    {
        "resource": "resource3",
        "name": "Resource 3",
        "resource_type_id": 1,
        "timezone": "US/Eastern"
    }
] (stacktrace: #0 /usr/share/xdmod/classes/Xdmod/Config.php(97): CCR\Json::loadFile('/etc/xdmod/reso...')
#1 /usr/share/xdmod/classes/Xdmod/Config.php(64): Xdmod\Config->loadSection('resources')
#2 /usr/share/xdmod/classes/OpenXdmod/Shredder.php(1044): Xdmod\Config->offsetGet('resources')
#3 /usr/share/xdmod/classes/OpenXdmod/Shredder.php(266): OpenXdmod\Shredder->getResourceConfig('mycluster')
#4 /usr/bin/xdmod-shredder(189): OpenXdmod\Shredder->setResource('mycluster')
#5 /usr/bin/xdmod-shredder(22): main()
#6 {main})
```

this is my json file (i copied from documentation)
```
[
    {
        "resource": "mycluster",
        "name": "My Cluster"
        "description": "Our first HPC resource",
        "resource_type_id": 1
    },
    {
        "resource": "resource2",
        "name": "Resource 2",
        "resource_type_id": 2,
        "pi_column": "account_name"
    },
    {
        "resource": "resource3",
        "name": "Resource 3",
        "resource_type_id": 1,
        "timezone": "US/Eastern"
    }
]
```

**Comment by jtpalmer** [comment]
You're missing a comma on line 4, after `"name": "My Cluster"`.  Add a comma at the end of that line and please try again.

**Comment by sazearte** [comment]
yes thanks, your documentation have this error with ressource.json : http://open.xdmod.org/configuration.html


I have a little difficulty understanding how to link open XDMoD to slurm, what is the simplest solution ?

**Comment by jtpalmer** [comment]
Have you looked at http://open.xdmod.org/resource-manager-slurm.html?  Open XDMoD includes a script called `xdmod-slurm-helper` which is intended to make integration with slurm easier.  It does require that `sacct` is installed on the same machine that is running Open XDMoD.

**Comment by sazearte** [comment]
ok, 
I was looking for the right place, thank you
