### ISSUE TITLE
install bugs

### ISSUE THREAD

**Issue by lilonghua1987** [ubccr/xdmod#61]
## Expected Behavior

Normal we can see a login window.

## Current Behavior

When i open the xdmod web server, show a window "Aggregate table not found, have you ingested your data?
#0 {main}".
And install xdmod log show "2017-03-02 05:26:41 [info] OpenXdmod\Ingestor\Hpcdb\ResourceTypes: Querying...
2017-03-02 05:26:41 [info] Executing SQL statement (host: localhost, port: 3306, username: xdmod, database: modw, statement: load data local infile '/tmp/resourcetype.data.3306.ipzzzc' replace into table resourcetype fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,abbrev,description))
2017-03-02 05:26:41 [error] Command returned non-zero value '1': ERROR 1366 (HY000) at line 1: Incorrect integer value: '' for column 'id' at row 1 (stacktrace: #0 /data/xdmod/share/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
#1 /data/xdmod/share/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
#2 /data/xdmod/share/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
#3 /data/xdmod/share/classes/OpenXdmod/DataWarehouseInitializer.php(373): PDODBMultiIngestor->ingest()
#4 /data/xdmod/share/classes/OpenXdmod/DataWarehouseInitializer.php(337): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
#5 /data/xdmod/share/classes/OpenXdmod/DataWarehouseInitializer.php(239): OpenXdmod\DataWarehouseInitializer->ingestAllHpcdb(NULL, NULL)
#6 /data/xdmod/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
#7 /data/xdmod/bin/xdmod-ingestor(21): main()
#8 {main}, statement: load data local infile '/tmp/resourcetype.data.3306.ipzzzc' replace into table resourcetype fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,abbrev,description))" ,
after we executor script “xdmod-ingestor -v”

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Node.js 5.4):
* Operating system and version (desktop or mobile):
* Link to your project:

**Comment by jtpalmer** [comment]
This looks more like an ingestion problem than a installation problem.  Is this a new install or did you upgrade?  What changed since the time when you could view the portal?

Please run this query in MySQL and reply with the results:

```sql
SELECT * FROM mod_hpcdb.hpcdb_resource_types;
```

Also, please include the contents of your `resource_types.json` file (`/data/xdmod/etc/resource_types.json`) in your reply.

**Comment by jtpalmer** [comment]
@lilonghua1987 , are you still having issues?  Please let us know.

**Comment by utkarsh123bholu** [comment]
I have the same error..
this is output for SELECT * FROM mod_hpcdb.hpcdb_reso

+---------+-----------+-----------------------+
| type_id | type_abbr | type_desc             |
+---------+-----------+-----------------------+
|       0 | UNKNOWN   | Unknown resource type |
|       1 | Default   | Default Resource Type |
+---------+-----------+-----------------------+
this is output for resources_types.json

[
    {
        "id": 1,
        "abbrev": "Default",
        "description": "Default Resource Type"
    }
]

**Comment by jtpalmer** [comment]
This looks like a `sql_mode` issue.  There is a bug that is converting `0` into the empty string.  Please set `sql_mode=''` and test with that.

**Comment by utkarsh123bholu** [comment]
Thanks for that. I have set sql_mod= ' '  and i am not getting any errors. But still i am getting that page only.
 When i open the xdmod web server, show a window "Aggregate table not found, have you ingested your data?
#0 {main}".


2017-07-05 22:45:14 [notice] Shredded 107870 records total
2017-07-05 22:45:14 [notice] Done shredding files
2017-07-05 22:45:14 [notice] Job errors written to '/tmp/xdmod_shredder_job_errors-H2M68P'
2017-07-05 22:45:14 [notice] Normalizing data
2017-07-05 22:45:14 [info] Started ingestion for class: PDODBMultiIngestor
2017-07-05 22:45:14 [info] PDODBMultiIngestor: Querying...
2017-07-05 22:45:14 [info] PDODBMultiIngestor: Rows Processed: 0 of 0 (Time Taken: 0.14 s)
2017-07-05 22:45:14 [notice] Finished ingestion (class: PDODBMultiIngestor, start_time: 1499274914.453, end_time: 1499274914.5939, records_examined: 0, records_loaded: 0)
2017-07-05 22:45:14 [notice] Done normalizing data
2017-07-05 22:45:14 [notice] xdmod-shredder end (process_end_time: 2017-07-05 22:45:14)

**Comment by jtpalmer** [comment]
You need to run `xdmod-ingestor` after you've shredded your data.  If there was a problem with the initial shredding you should run `xdmod-admin --truncate --jobs` (this will delete all job data), then the `xdmod-shredder` command and then `xdmod-ingestor`.

**Comment by utkarsh123bholu** [comment]
Thank you so much finally i have got it. Thanks for your help @jtpalmer. Actually i am working on a project and i need to enhance atleast one feature in xdmod. Hope you will help me in future too.. thanks
